# Generated by Django 3.1.1 on 2020-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200912_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bans',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bans',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
