# Generated by Django 3.1.5 on 2021-11-22 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('issue_datetime', models.DateTimeField(auto_now_add=True)),
                ('exp_datetime', models.DateTimeField()),
                ('purpose', models.TextField()),
                ('allowed_requests', models.IntegerField(default=100)),
                ('status', models.CharField(default='Active', max_length=24)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_by', to=settings.AUTH_USER_MODEL, verbose_name='ID выпустившего API-key')),
            ],
        ),
        migrations.CreateModel(
            name='APIRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=16, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('APIKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='APIKey', to='API.apikey', verbose_name='Api-key')),
            ],
        ),
    ]
