# Generated by Django 3.1.5 on 2021-11-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API-key', 'verbose_name_plural': 'API-keys'},
        ),
        migrations.AlterModelOptions(
            name='apirequests',
            options={'verbose_name': 'API запрос', 'verbose_name_plural': 'API запросы'},
        ),
    ]
