# Generated by Django 3.1.5 on 2021-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_apikey_super_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequests',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
