# Generated by Django 3.1.5 on 2021-12-08 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0005_apirequests_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=64, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Право API',
                'verbose_name_plural': 'Права API',
            },
        ),
        migrations.AlterField(
            model_name='apikey',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='APIKey', to=settings.AUTH_USER_MODEL, verbose_name='ID выпустившего API-key'),
        ),
        migrations.AlterField(
            model_name='apirequests',
            name='APIKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='APIRequests', to='API.apikey', verbose_name='Api-key'),
        ),
        migrations.CreateModel(
            name='APIKeys_Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='APIKeys_Permissions', to='API.apikey', verbose_name='Api-key')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='APIKeys_Permissions', to='API.apipermissions', verbose_name='API permission')),
            ],
            options={
                'verbose_name': 'Отношение права API',
                'verbose_name_plural': 'Отношения прав API',
            },
        ),
    ]
