# Generated by Django 3.1.5 on 2021-12-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20211208_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikeys_permissions',
            old_name='key_id',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='apikeys_permissions',
            old_name='permission_id',
            new_name='permission',
        ),
    ]
