# Generated by Django 3.1.5 on 2021-12-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20211208_2331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apikeys_permissions',
            unique_together={('key', 'permission')},
        ),
    ]
