# Generated by Django 3.0.8 on 2020-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('pub_datetime', models.DateTimeField()),
                ('lasted_datetime', models.DateTimeField()),
                ('author', models.CharField(max_length=24)),
                ('tags', models.TextField()),
                ('status', models.CharField(max_length=24)),
            ],
        ),
    ]
