# Generated by Django 3.0.8 on 2020-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_articles_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='lasted_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
