# Generated by Django 3.1.5 on 2021-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20210109_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='user_ip',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
