# Generated by Django 3.0.8 on 2020-07-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200727_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_datetime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
