# Generated by Django 3.1.5 on 2021-01-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_views_user_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'permissions': (('restore_articles', 'Can restore Articles'), ('publish_articles', 'Can publish drafts of Articles'), ('view_published', 'Can view published Articles'), ('view_draft', 'Can view drafts of Articles'), ('view_deleted', 'Can view deleted Articles')), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
