# Generated by Django 4.0 on 2021-12-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0005_auto_20210112_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_datetime', models.DateTimeField(blank=True, null=True)),
                ('rating_type', models.CharField(default='Default', max_length=24)),
                ('rating_weight', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.articles', verbose_name='Статья')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
