# Generated by Django 3.1.1 on 2020-09-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200911_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bans',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
