# Generated by Django 4.0 on 2021-12-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0006_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'permissions': (('give_rating', 'Can give rating to articles'), ('manage_rating', 'Can manage rating of articles')), 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rating', to='Main.articles', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Given_rating', to='auth.user', verbose_name='Пользователь'),
        ),
    ]
