# Generated by Django 3.1.1 on 2020-09-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200911_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bans',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
