# Generated by Django 4.0 on 2021-12-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0007_alter_rating_options_alter_rating_article_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('article', 'user')},
        ),
    ]
