# Generated by Django 3.1.1 on 2020-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200912_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
