# Generated by Django 4.0 on 2021-12-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(default='Active', max_length=24),
        ),
    ]
