# Generated by Django 4.0 on 2022-01-12 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0014_alter_comments_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Reported', to='Main.articles', verbose_name='Статья')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Reported', to='Main.comments', verbose_name='Комменатрий')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('report_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=24)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reports', to='Main.reportable', verbose_name='Объект жалобы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reported', to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'permissions': (('consider_reports', 'Can consider Reports'), ('review_reports', 'Can review Reports')),
            },
        ),
        migrations.AddConstraint(
            model_name='reportable',
            constraint=models.CheckConstraint(check=models.Q(('article', None), ('comment', None), _connector='OR'), name='one_field_none'),
        ),
    ]
