# Generated by Django 4.0 on 2022-01-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_reporttypes_reports_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttypes',
            options={'verbose_name': 'Тип жалобы', 'verbose_name_plural': 'Типы жалоб'},
        ),
    ]
